- name: idflab folders
  file:
    path: "/home/{{ item }}/idflab/"
    owner: "{{ item }}"
    state: directory
  with_items: "{{ student_users }}"
  tags: snap_binary

- name: snap ubuntu package
  get_url:
    url: http://xenial.pkg.dl.snap-telemetry.io
    dest: "/home/{{ item }}/idflab/snap-telemetry_0.15.0-1xenial_amd64.deb"
    mode: "0644"
  with_items: "{{ student_users }}"
  tags: snap_binary

- name: snap plugins
  get_url:
    url: http://linux.tar.dl.snap-telemetry.io
    dest: "/home/{{ item }}/idflab/snap-plugins.tar.gz"
    mode: "0644"
  with_items: "{{ student_users }}"
  tags: snap_binary

# Download containers
- name: cache container images
  docker_image:
    name: "{{ item.value.name }}"
    tag:  "{{ item.value.tag }}"
  with_dict:
    snap-slim:
      name: nanliu/snap-slim
      tag: latest
      repo: localhost:5000/snap
    heapster-slim:
      name: nanliu/heapster-slim
      tag: latest
      repo: localhost:5000/heapster-snap
    addon-resizer:
      name: gcr.io/google_containers/addon-resizer
      tag: 1.0
      repo: localhost:5000/addon-resizer
    influxdb-grafana:
      name: nanliu/grafana-snap
      tag: latest
      repo: localhost:5000/grafana-snap
    influxdb:
      name: gcr.io/google_containers/heapster_influxdb
      tag: v0.5
      repo: localhost:5000/heapster_influxdb
    hpa-example:
      name: gcr.io/google_containers/hpa-example
      tag: latest
      repo: localhost:5000/hpa-example
  tags: containers

# Tag containers localhost:5000
- name: cache container images
  docker_image:
    name: "{{ item.value.name }}"
    repository: "{{ item.value.repo }}"
    tag:  "{{ item.value.tag }}"
  with_dict:
    snap-slim:
      name: nanliu/snap-slim
      tag: latest
      repo: localhost:5000/snap
    heapster-slim:
      name: nanliu/heapster-slim
      tag: latest
      repo: localhost:5000/heapster-snap
    addon-resizer:
      name: gcr.io/google_containers/addon-resizer
      tag: 1.0
      repo: localhost:5000/addon-resizer
    influxdb-grafana:
      name: nanliu/grafana-snap
      tag: latest
      repo: localhost:5000/grafana-snap
    influxdb:
      name: gcr.io/google_containers/heapster_influxdb
      tag: v0.5
      repo: localhost:5000/heapster_influxdb
    hpa-example:
      name: gcr.io/google_containers/hpa-example
      tag: latest
      repo: localhost:5000/hpa-example
    minikube:
      name: gcr.io/google_containers/echoserver
      tag: 1.4
      repo: localhost:5000/echoserver
    registry-proxy:
      name: gcr.io/google_containers/kube-registry-proxy
      tag: 0.3
      repo: localhost:5000/kube-registry-proxy
  tags: containers

- name: copy push container image script
  copy:
    src: push_images
    dest: /usr/local/bin/push_images
    owner: root
    group: root
    mode: '0755'

# NOTE: Intel PCM plugin requirements:
- name: /opt/intel foder
  file:
    path: /opt/intel
    state: directory

- name: intel pcm 2.11
  unarchive:
    dest: /opt/intel
    src: IntelPerformanceCounterMonitor-V2.11.zip
  ignore_errors: True #NOTE: cleanup later

- name: make pcm
  shell: make
  args:
    chdir: /opt/intel/IntelPerformanceCounterMonitor-V2.11
    creates: /opt/intel/IntelPerformanceCounterMonitor-V2.11/pcm.x

- name: pcm.x binary
  file:
    dest: /usr/local/bin/pcm.x
    src: /opt/intel/IntelPerformanceCounterMonitor-V2.11/pcm.x
    state: link

- name: enable msr
  modprobe:
    name: msr
    state: present

- name: disable kernel.nmi_watchdog=0
  sysctl:
    name: kernel.nmi_watchdog
    value: 0
    state: present

- name: pcm ksysguard example
  copy:
    dest: /home/{{ item }}/idflab/intel_pcm.sgrd
    src:  intel_pcm.sgrd
  with_items: "{{ student_users }}"
