---
- hosts: lenovo
  become: yes
  become_user: root
  become_method: sudo
  environment:
    http_proxy: http://proxy-chain.intel.com:911
    https_proxy: http://proxy-chain.intel.com:911
  roles:
    - accounts
    #- hidpi
    - docker
    - vagrant
    - kargo
